- name: Register evercam-media local commit hash
  local_action:
    shell
    chdir={{local_media_dir}}
    git rev-parse --short HEAD
  register: local_commit_hash

- name: Delete build directory
  file: path="{{build_dir}}" state=absent

- name: Clone evercam-media
  git:
    repo: https://github.com/evercam/evercam-media
    dest: "{{build_dir}}/"
    version: "{{local_commit_hash.stdout}}"

- name: Get evercam-media dependencies
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix deps.get'"
  args:
    chdir: "{{build_dir}}"

- name: Compile evercam-media application
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix compile'"
  args:
    chdir: "{{build_dir}}"
  failed_when: False

- name: Compile again so any flaky dependencies are recompiled
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix compile'"
  args:
    chdir: "{{build_dir}}"

- name: Build evercam-media application release
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix release'"
  args:
    chdir: "{{build_dir}}"

- name: Register the version of the release
  shell: "cat {{build_dir}}/rel/evercam_media/releases/start_erl.data | awk '{print $2}'"
  register: evercam_media_version

- name: Ensure there is a directory for the application
  file: path="{{remote_media_dir}}" state=directory

- name: Copy the release to the application directory
  unarchive:
    copy: no
    src: "{{build_dir}}/rel/evercam_media/releases/{{evercam_media_version.stdout}}/evercam_media.tar.gz"
    dest: "{{remote_media_dir}}"

- name: Check if motion detection file exists
  stat:
    path: "{{build_dir}}/priv_dir/elixir_motiondetection.so"
  register: motion_detection_file

- name: Ensure priv_dir exists
  file: path="{{remote_media_dir}}/priv_dir" state=directory
  when: motion_detection_file.stat.exists == True

- name: Copy motion detecion file
  shell: "cp {{build_dir}}/priv_dir/elixir_motiondetection.so {{remote_media_dir}}/priv_dir/"
  when: motion_detection_file.stat.exists == True

