- hosts: "{{target}}"
  user: "{{ansible_ssh_user}}"
  vars_files:
    - vars.yml
    - ../../private_vars_media.yml
  vars:
    - production: True
    - user_name: "{{ansible_ssh_user}}"
  roles:
    - deps
    - ANXS.postgresql
    - ffmpeg
    - nginx
    - media