- hosts: all
  user: "{{user_name}}"
  sudo: yes
  vars_files:
    - vars.yml
    - ../private_vars.yml
  roles:
    - deps
    - heroku-toolbelt
    - rvm_io.rvm1-ruby
    - ANXS.postgresql
    - DavidWittman.redis
    - geerlingguy.memcached
    - evercam
